"""phase 1: production lines, signatures, audit templates, attachments

Revision ID: f96dbb32b6ce
Revises: e69be66b7d27
Create Date: 2026-07-25 08:52:44.559290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96dbb32b6ce'
down_revision: Union[str, None] = 'e69be66b7d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_templates',
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standard', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_templates_company_id'), 'audit_templates', ['company_id'], unique=False)
    op.create_table('audit_template_items',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('clause', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_template_items_template_id'), 'audit_template_items', ['template_id'], unique=False)
    op.create_table('attachments',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_table('digital_signatures',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('meaning', sa.String(length=50), nullable=False),
    sa.Column('signed_by_id', sa.String(length=36), nullable=False),
    sa.Column('typed_name', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_signatures_entity_id'), 'digital_signatures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_digital_signatures_entity_type'), 'digital_signatures', ['entity_type'], unique=False)
    op.create_index(op.f('ix_digital_signatures_signed_by_id'), 'digital_signatures', ['signed_by_id'], unique=False)
    op.create_table('production_lines',
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('line_type', sa.String(length=100), nullable=True),
    sa.Column('capacity_per_hour', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_facility_id'), 'production_lines', ['facility_id'], unique=False)
    op.create_table('audit_ai_analyses',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('generated_by_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('recommended_corrective_actions', sa.Text(), nullable=True),
    sa.Column('improvement_plan', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_ai_analyses_audit_id'), 'audit_ai_analyses', ['audit_id'], unique=False)
    op.create_table('audit_checklist_items',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('template_item_id', sa.String(length=36), nullable=True),
    sa.Column('clause', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('corrective_action_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrective_action_id'], ['corrective_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_item_id'], ['audit_template_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checklist_items_audit_id'), 'audit_checklist_items', ['audit_id'], unique=False)
    op.add_column('audits', sa.Column('template_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'audits', 'audit_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audits', type_='foreignkey')
    op.drop_column('audits', 'template_id')
    op.drop_index(op.f('ix_audit_checklist_items_audit_id'), table_name='audit_checklist_items')
    op.drop_table('audit_checklist_items')
    op.drop_index(op.f('ix_audit_ai_analyses_audit_id'), table_name='audit_ai_analyses')
    op.drop_table('audit_ai_analyses')
    op.drop_index(op.f('ix_production_lines_facility_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_digital_signatures_signed_by_id'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_entity_type'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_entity_id'), table_name='digital_signatures')
    op.drop_table('digital_signatures')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_audit_template_items_template_id'), table_name='audit_template_items')
    op.drop_table('audit_template_items')
    op.drop_index(op.f('ix_audit_templates_company_id'), table_name='audit_templates')
    op.drop_table('audit_templates')
    # ### end Alembic commands ###
