from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.core.deps import get_current_active_user, get_db
from app.models.ai import AIConversation, AIMessage
from app.models.document import Document, DocumentVersion
from app.models.enums import DocumentCategory
from app.models.user import User
from app.schemas.ai import (
    AIChatRequest,
    AIConversationRead,
    AIGenerateRequest,
    AIGenerateResponse,
    AIMessageRead,
)
from app.services.ai import get_ai_provider
from app.services.ai.company_context import build_company_context
from app.services.ai.prompts import QA_SYSTEM_PROMPT, get_document_system_prompt

MAX_HISTORY_MESSAGES = 12

router = APIRouter()

DOC_CATEGORY_MAP = {
    "haccp_plan": DocumentCategory.HACCP_PLAN,
    "sop": DocumentCategory.SOP,
    "cleaning_procedure": DocumentCategory.SOP,
    "policy": DocumentCategory.POLICY,
    "training_material": DocumentCategory.TRAINING_RECORD,
    "audit_report": DocumentCategory.OTHER,
    "risk_assessment": DocumentCategory.OTHER,
    "corrective_action": DocumentCategory.OTHER,
    "supplier_evaluation": DocumentCategory.SUPPLIER_DOCUMENT,
}


@router.post("/generate", response_model=AIGenerateResponse)
async def generate_document(
    payload: AIGenerateRequest,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    provider = get_ai_provider()
    system_prompt = get_document_system_prompt(payload.document_type)
    try:
        content = await provider.complete(system_prompt, payload.prompt)
    except Exception as exc:  # provider/network errors surface as a clean 503
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc)) from exc

    document_id = None
    if payload.save_as_document:
        document = Document(
            company_id=current_user.company_id,
            owner_id=current_user.id,
            title=payload.document_title or f"AI-generated {payload.document_type.replace('_', ' ')}",
            category=DOC_CATEGORY_MAP.get(payload.document_type, DocumentCategory.OTHER),
            description=f"Generated by AI Assistant from prompt: {payload.prompt[:200]}",
        )
        db.add(document)
        db.flush()
        document.versions.append(DocumentVersion(uploaded_by_id=current_user.id, version=1, content_text=content))
        db.commit()
        document_id = document.id

    return AIGenerateResponse(content=content, document_id=document_id)


@router.post("/chat", response_model=AIConversationRead)
async def chat(
    payload: AIChatRequest,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    if payload.conversation_id:
        conversation = db.get(AIConversation, payload.conversation_id)
        if not conversation or conversation.user_id != current_user.id:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    else:
        conversation = AIConversation(
            user_id=current_user.id,
            company_id=current_user.company_id,
            title=payload.message[:60],
        )
        db.add(conversation)
        db.flush()

    conversation.messages.append(AIMessage(role="user", content=payload.message))
    db.flush()

    context = build_company_context(db, current_user.company_id, payload.message)
    transcript = "\n".join(
        f"{'User' if m.role == 'user' else 'Assistant'}: {m.content}"
        for m in conversation.messages[-MAX_HISTORY_MESSAGES:]
    )
    user_prompt = (
        f"Relevant company data:\n{context}\n\nConversation so far:\n{transcript}" if context else transcript
    )

    provider = get_ai_provider()
    try:
        reply = await provider.complete(QA_SYSTEM_PROMPT, user_prompt)
    except Exception as exc:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc)) from exc

    conversation.messages.append(AIMessage(role="assistant", content=reply))
    db.commit()
    db.refresh(conversation)
    return conversation


@router.get("/conversations", response_model=list[AIConversationRead])
def list_conversations(current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)):
    return (
        db.query(AIConversation)
        .filter(AIConversation.user_id == current_user.id)
        .order_by(AIConversation.created_at.desc())
        .all()
    )


@router.get("/conversations/{conversation_id}", response_model=AIConversationRead)
def get_conversation(
    conversation_id: str, current_user: User = Depends(get_current_active_user), db: Session = Depends(get_db)
):
    conversation = db.get(AIConversation, conversation_id)
    if not conversation or conversation.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    return conversation
